# Generated by Django 3.1.3 on 2021-09-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('isbn_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField()),
                ('page_count', models.IntegerField()),
                ('book_cover_link', models.CharField(blank=True, max_length=255)),
                ('publication_language', models.CharField(blank=True, max_length=255)),
                ('authors', models.ManyToManyField(blank=True, to='api.Author')),
                ('isbns', models.ManyToManyField(blank=True, to='api.ISBN')),
            ],
        ),
    ]
