# Generated by Django 3.2.7 on 2021-09-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True)),
                ('book_cover_link', models.CharField(blank=True, max_length=255)),
                ('publication_language', models.CharField(blank=True, max_length=255)),
                ('authors', models.ManyToManyField(blank=True, to='api.Author')),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('isbn_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
    ]
